### ISSUE TITLE
Jobs Upsell Items with Stripe Tracking

### ISSUE THREAD

**Issue by coderberry** [gitcoinco/code_fund_ads#307]
- [x] Offer verbiage is correct
- [ ] Determine and implement cap of 75k impressions
- [x] Slack notification (or email) for upsells
- [x] Add premium (above the fold) for upsells
- [x] Confirm RTD verbiage w/ David
- [x] Clean-up fixed-pricing coupon cruft

**Comment by hopsoft** [comment]
We'll have to revisit the 75k impression cap later. For now I think we can manually configure the campaign and monitor its performance.
