### ISSUE TITLE
Remaining for MVP

### ISSUE THREAD

**Issue by coderberry** [gitcoinco/code_fund_ads#88]
# What's Left

## General

- [x] Un-masquerade doesn't work (@codeberry) _may not be an issue_
- [x] #89 - Top nav needs fixing (@coderberry)
- [x] #91 Redo front page image (@coderberry)
- [ ] Ensure page looks good on Safari / Firefox (@coderberry)
- [x] Update README to say "app in dev mode needs cache to do everything" (@coderberry)
- [x] Download maxmind throwing error (@hopsoft) #94 
- [x] #98 Support legacy URL's for publishers (@coderberry)
- [x] #96 Add sentry error reporting (@coderberry)

### Applicants (Not MVP)

- [ ] Set up notifications (@coderberry)
- [ ] Auto approve/reject applicants with button (@coderberry)

### Dashboard

- [x] #93 Missing admin dashboard (low) (@coderberry)
- [x] #93 Missing advertiser dashboard (@coderberry then data by @hopsoft)
- [x] #93 Publisher dashboard missing (@coderberry then data by @hopsoft)

#### Properties

- [x] Property card needs to show real stats (@hopsoft)

## Campaigns

- [x] Update stats on dashboard (@hopsoft)
- [x] #100 Details needs to show "refresh screenshot" button (admin only) (@coderberry)
- [x] Budgets need to show data for dates (likely paginated) (@hopsoft)
- [x] Nate might add ___ gem on budget tab (@hopsoft)
- [x] #103 Properties tab UI love (@coderberry)
- [x] Properties tab needs stats (nate) (@hopsoft)
- [x] #102 Remove "advertiser" from table when logged in as advertiser (@coderberry)
- [ ] Add remaining budget to table (@hopsoft)
- [ ] Add CTR to table (@hopsoft)

### Properties

- [x] Dashboard needs data (@hopsoft)
- [x] #103 Embed instructions needs love (or seperate tab) (@coderberry)
- [x] #97 Earnings (THIS IS BIG) (@hopsoft)
- [x] Campaigns table might need Nate love (@hopsoft)
- [ ] Distributions doesn't exist (@hopsoft)
- [x] #102 Remove "publisher" from table when logged in as publisher (@coderberry)
- [ ] Add earnings to table (@hopsoft)
- [ ]  Add CTR to table (@hopsoft)
- [x] Allow editing of ad_template, ad_theme, prohibited_advertiser_ids, prohibit_fallback_campaigns, revenue_percentage (@coderberry)

### Creatives

- [ ] Stats on creative cards (@hopsoft)
- [x] Missing show page for creative. This will show all templates and stats for this creative. (@coderberry)
- [x] Add "We are working on this" note on show page (@coderberry)

### Images

- [x] Unable to upload images on stage/prod (@coderberry)
- [x] Allow images to appear direct from cdn2.codefund.app (cloudfront) (@hopsoft)

### Inbound Funds

- [x] TO DO (@coderberry)

### Distributions

- [ ] TO DO (@hopsoft)
